name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: "macos-latest"
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install '.[build]'

      - name: Build distribution
        run: python -m build

      - name: Publish distribution 📦 to PyPI
        run: python -m twine upload dist/*
        env:
          # Get token from https://pypi.org/manage/account/token/
          # Set token in https://github.com/thewh1teagle/nakdimon-ort/settings/secrets/actions/new
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
